path: . # path to 'datasets' folder
train:
  - train\images
val:
  - val\images
test:
  - test\images

# Modify "nc" according to the number of labels
nc: 6

names: ['Cable_connector','Device','Lugs','Thickcables_of_othercolor','Thin_cables','White/green_thickcable']
